### ISSUE TITLE
Source release still planned?

### ISSUE THREAD

**Issue by polygon** [s-a/sonic-sound-picture#10]
In https://github.com/s-a/sonic-sound-picture/issues/3 a user asked for source code and your initial response seemed to indicate that you are planning to release the source once certain issues were fixed. Few weeks later, the issue was closed as "not planned" without further comment.

Does this mean that you are no longer planning to release the source code?

**Comment by s-a** [comment]
I still plan to release the source code once the product is stable and robust.
 
To ensure that the released source code is maintainable and easy to develop further, I plan to include guidelines and documentation that explain the architecture and codebase to help other developers understand the code more easily and can facilitate contributions to the project. But it takes some efforts and time. Time is the most important problem here, while I also focus on producing content (templates) for the software and I have only a few hours per week for this project.

I also need to solve some problems with the compile and release pipeline in Github actions where I only have a small amount of free cpu time quota. The current pipeline does not include windows yet, but I need it to be full automated finaly.

I already started to publish a part for template creators at https://github.com/s-a/easy-ssp/ which is a Blender Addon

**Comment by s-a** [comment]
The source is now available at https://github.com/s-a/sonic-sound-picture/tree/main/electron-app
