### ISSUE TITLE
"Your machine configuration is not fine yet." but it seems ok to me.

### ISSUE THREAD

**Issue by AlexxArtificial** [s-a/sonic-sound-picture#13]
![image](https://user-images.githubusercontent.com/130026577/230272171-0cff4f55-e9a6-45e3-8df2-dd3a46293f16.png)

**Comment by AlexxArtificial** [comment]
![image](https://user-images.githubusercontent.com/130026577/230282197-f92500f2-577a-4cb3-b9b2-699e577d1b56.png)

**Comment by s-a** [comment]
resolved on discord as not a bug. change `blender-launcher.exe` to `blender.exe` resolves the problem.
