### ISSUE TITLE
Can I use GPU Render video？

### ISSUE THREAD

**Issue by buggzd** [s-a/sonic-sound-picture#15]
When I render the video, I found that it's using my CPU instead of my GPU.Is there a way to render the video using a GPU?
![QQ_1721579430592](https://github.com/user-attachments/assets/e8d7492f-2e58-4ad6-b1df-394b4b10c079)
![QQ_1721579385862](https://github.com/user-attachments/assets/2c384cc7-3b36-4bc6-8b53-c23b9fe50b13)
![QQ_1721579647930](https://github.com/user-attachments/assets/b1a8f795-80dc-4456-9b90-7536b6f53e55)

**Comment by s-a** [comment]
GPU should render by default when SSP sets EEVEE engine to render.
https://github.com/s-a/sonic-sound-picture/blob/main/electron-app/src/static/render.py#L474
You can inspect the problem when you render to `.blend` instead of `video` in the type dropdown.
 Then open the file with Blender to see what is going on.

**Comment by s-a** [comment]
# CPU Rendering
Being a rasterization engine, EEVEE only uses the power of the GPU to render. There is no plan to support CPU (software) rendering as it would be very inefficient. CPU power is still needed to handle high scene complexity as the geometry must be prepared by the CPU before rendering each frame.

ref.: https://docs.blender.org/manual/en/latest/render/eevee/limitations.html#cpu-rendering

**Comment by buggzd** [comment]
> # CPU Rendering
> Being a rasterization engine, EEVEE only uses the power of the GPU to render. There is no plan to support CPU (software) rendering as it would be very inefficient. CPU power is still needed to handle high scene complexity as the geometry must be prepared by the CPU before rendering each frame.
> 
> ref.: https://docs.blender.org/manual/en/latest/render/eevee/limitations.html#cpu-rendering

w(ﾟДﾟ)w，Thanks!!! It is usefull.
