### ISSUE TITLE
Blender executable cannot be selected on macOS

### ISSUE THREAD

**Issue by beingalink** [s-a/sonic-sound-picture#7]
Applications on macOS are app bundles, which itself are just folders that have a special marking to be presented like files in Finder app and contain the main binary, helpers, config files, and materials like images, documents, etc. The file picker in ssp can't look into the blender app bundle to select the main binary because the blender app appears like a file.

You can work around this by adding the path for blender manually in the `config.json`. You can find this file under `/Users/<username>/Library/Application Support/ssp/config.json`.

To find out about the path of the blender binary, you right-click the app bundle and select 'View Package Contents'. On my m1 mac, the path to the binary is `/Applications/Blender.app/Contents/MacOS/Blender`, not sure if it's different on intel macs.

Then you open the `config.json`file from above and insert the following line for blender:
```
{
	"executables": {
		"blender": "/Applications/Blender.app/Contents/MacOS/Blender",
		...
	},
	...
}
```

Then you restart ssp and in the settings tab there should be the correct path displayed for blender.

**Comment by now-its-dark** [comment]
You can also get around this by creating an alias to the blender executable that is within the app package, then selecting that alias from the file picker instead.

**Comment by s-a** [comment]
resolved in https://github.com/s-a/sonic-sound-picture/releases/tag/1.0.13
